name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: fedora-latest

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          tools: composer
          extensions: pgsql, pdo_pgsql

      - uses: actions/checkout@v4

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: composer install

      - name: Generate key
        run: php artisan key:generate

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Setup PostgreSQL
        run: sudo dnf install -y postgresql-server postgresql-contrib

      - name: Initialize PostgreSQL Database
        run: |
          sudo postgresql-setup --initdb --unit postgresql
          sudo systemctl start postgresql
          sudo systemctl enable postgresql
          sudo -u postgres psql -c "CREATE USER laravel WITH PASSWORD 'password';"
          sudo -u postgres psql -c "CREATE DATABASE laravel_test;"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE laravel_test TO laravel;"

      - name: Update .env for PostgreSQL
        run: |
          sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=pgsql/' .env
          sed -i 's/DB_HOST=127.0.0.1/DB_HOST=localhost/' .env
          sed -i 's/DB_PORT=3306/DB_PORT=5432/' .env
          sed -i 's/DB_DATABASE=laravel/DB_DATABASE=laravel_test/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=laravel/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env

      - name: Run Migrations
        run: php artisan migrate

      - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
        env:
          DB_CONNECTION: pgsql
          DB_HOST: localhost
          DB_PORT: 5432
          DB_DATABASE: laravel_test
          DB_USERNAME: laravel
          DB_PASSWORD: password
        run: php artisan test
