name: Check & fix styling

on:
  push:
    paths:
      - '.github/workflows/**'
      - '**.php'
      - 'phpunit.xml'
      - 'composer.json'
      - 'composer.lock'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP 🔧
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: composer:v2
        env:
          COMPOSER_TOKEN: ${{ secrets.TOKEN }}

      - name: Update Composer Dependencies 🔧
        run: composer update -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Install Composer Dependencies 🔧
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Run Pint
        run: vendor/bin/pint

      - name: Set up Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        id: git_commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fixed code style
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          branch: ${{ github.head_ref }}

      - name: Check if commit was made
        run: |
          if [ $(git log -1 --pretty=%B) != "Fixed code style" ]; then
            echo "No changes to commit"
            exit 0
          fi
